### ISSUE TITLE
Anyone with the link note sharing

### ISSUE THREAD

**Issue by john-nguyen09** [bee-jee/bee-jee#19]
## Background

The anyone with the link is already implemented in the app. However, there is no URL displayed to send.

## TODO

- [x] Create tests for when the permission is changed from "Anyone with the link" to "Private" or "Users", details are below.
- [x] When selecting the "Anyone with the link" option, a section will display to show the URL to ViewShared component.
![image](https://user-images.githubusercontent.com/18049577/89359711-c8b1e280-d709-11ea-9864-e2944794a67f.png)
- [x] Test and make sure when the user clicks on the link, the note will appear under "Shared note" section
- [x] Test and make sure when the author changes the permission to private or public, the note is removed from "Shared note" section of anyone who have clicked on the link.
